### ISSUE TITLE
Add Leetcode Problems

### ISSUE THREAD

**Issue by Arindam200** [Arindam200/Python_Projects#115]
Add Leetcode Problems With the Question.
First, Make a folder with The Question name& number.
Make a Readme then add the Code & Question along with the question link.

Here is an example:
![Screenshot (50)](https://user-images.githubusercontent.com/109217591/194737619-45632f58-e9fe-40f5-97b6-af9a0bb822f6.png)

**Comment by smitioswal** [comment]
Please assign me

**Comment by smitioswal** [comment]
Do I have to add solution as well?

**Comment by Arindam200** [comment]
yes ! add both solution and question in a separate folder in the Leetcode_solution file.

**Comment by AkshayGidwani405** [comment]
Hi @Arindam200! I would like to contribute. Do assign me this issue.

**Comment by thechangamunda** [comment]
I would like to contribute as well assign me this issue.

**Comment by Arindam200** [comment]
@thechangamunda you can contribute

**Comment by thechangamunda** [comment]
Do I have to present the problem and  in the readme format or can I do it inside a .py extension file to make the problem and solution more easily accessible.

**Comment by Arindam200** [comment]
Add questions in the readme and ans in  .py file and make a saparate folder in leetcode_solutioj file

**Comment by Tanmaybhujade** [comment]
can you assign this issue to  me.

**Comment by Arindam200** [comment]
@Tanmaybhujade  Go for it!

**Comment by Tanmaybhujade** [comment]
I have added check it

**Comment by das-amit** [comment]
@Arindam200 I would also like to contribute

**Comment by Arindam200** [comment]
@das-amit yes can! Go for it!

**Comment by 9520prashant** [comment]
Hy, I am a DSA mentor can i have a chance to take this issue!

**Comment by Arindam200** [comment]
@9520prashant yes!!

**Comment by 9520prashant** [comment]
> @9520prashant yes!!  Tell me How can i help you??

**Comment by Arindam200** [comment]
@9520prashant do add some Good questions on Dsa

**Comment by Tanmaybhujade** [comment]
can you assign this issue to me.
