### ISSUE TITLE
Add Python Snake Game project

### ISSUE THREAD

**Issue by gazal2708** [Arindam200/Python_Projects#12]
Add a snake game in python which has following features:

1. Arena for snake to move
2. A snake with a finite speed
3. Food for snake to swallow
4. Snake length increases as it swallows the food
5. Scores should be displayed on screen.

**Comment by Arindam200** [comment]
Thanks, Gazal. You are too kind.
Keep contributing.

**Comment by gazal2708** [comment]
Hi @Arindam200 , I have left some comments on the PR which you recently merged related to this issue, can you please take a look at it and help me out.
