### ISSUE TITLE
Cluster projects

### ISSUE THREAD

**Issue by HeyAnirudh** [Arindam200/Python_Projects#134]
So in this repo, there are many python projects which belong to different domains .like ML, Web dev, etc 

so we could create sub folder like 

AI 
|
|__ Ai project 1
|__ Ai project 2 

etc

**Comment by Arindam200** [comment]
@HeyAnirudh  Thanks for pointing!
go for it!

**Comment by HeyAnirudh** [comment]
@Arindam200 hey i had a doubt, why isn't my contribution showing in hacktoberfest dashboard?
