### ISSUE TITLE
Can't Clone Repo

### ISSUE THREAD

**Issue by Akshat-kumar-jain** [Arindam200/Python_Projects#138]
![cantClone](https://user-images.githubusercontent.com/40888828/194929761-c0689019-5c13-457b-b109-1e428e89e04a.PNG)

**Comment by Akshat-kumar-jain** [comment]
Could anyone help me out with this?

**Comment by Akshat-kumar-jain** [comment]
I found a potential issue in the name of the folder "encryption&decryption.";
@Arindam200 Could you please remove the "." from the end of the folder name?

**Comment by Arindam200** [comment]
@Akshat-kumar-jain Thanks for pointing out!
