### ISSUE TITLE
Add projects in a separate folder

### ISSUE THREAD

**Issue by Arindam200** [Arindam200/Python_Projects#64]
**Add projects in a separate folder**

make separate folders for projects and add the codes.

![Screenshot (38)](https://user-images.githubusercontent.com/109217591/194010510-8247cf92-3b46-48da-ba1f-52d01524a309.png)

**Comment by Arindam200** [comment]
It should look like this!

![Screenshot (39)](https://user-images.githubusercontent.com/109217591/194011315-16402e27-8486-4cc3-8617-d00abc4c699a.png)

**Comment by rishabhknowss** [comment]
Please assign me the task

**Comment by Arindam200** [comment]
@rishabhknowss Go for it!

**Comment by vaibhavmishra4g** [comment]
i'm gonna do it right now!

**Comment by Tejesh18** [comment]
Hey,I would like to work on this.Please assign this to me.

**Comment by Tejesh18** [comment]
#108 Created separate folders and added files
