### ISSUE TITLE
Add Python Projects

### ISSUE THREAD

**Issue by Arindam200** [Arindam200/Python_Projects#8]
Description
Create Issues about the project you want to add.

**Comment by gazal2708** [comment]
I have added one new project and created a pull request. Please review it.

**Comment by Arindam200** [comment]
I have merged it Gazal, Thanks for your kind contribution.
Keep contributing.

**Comment by Tanmaybhujade** [comment]
I have added one new project and created a pull request
revivew it.

**Comment by kisbAlt** [comment]
Hey! I added a new joke teller project, and created a pull request for it. :)

**Comment by akash9579** [comment]
Hi @Arindam200 
Can u assign me this issue
I am happy to contribute on this.

**Comment by Arindam200** [comment]
Hey @akash9579 , You can contribute to this project!

**Comment by akash9579** [comment]
hey @Arindam200  will you please merge my PR #49

**Comment by Arindam200** [comment]
Hey @akash9579 
I've merged it!
Happy Hacktober!

**Comment by Atharv-777** [comment]
Het @Arindam200 can I add one project?

**Comment by Arindam200** [comment]
@Atharv-777  Yes!  You  Can! Go for it!

**Comment by arpitsengar99** [comment]
hey can you assign me to this project, i'll be more than happy to help

**Comment by Arindam200** [comment]
Hey @arpitsengar99 !  You can contribute! Go for it!

**Comment by Atharv-777** [comment]
> @Atharv-777 Yes! You Can! Go for it!

Hey @Arindam200 I've created a PR can you check it once

**Comment by Akshat-kumar-jain** [comment]
I want to contribute. Please assign me.

**Comment by Arindam200** [comment]
@Akshat-kumar-jain Go for It!

**Comment by Sirsha2468** [comment]
I want to contribute, can I do it?

**Comment by Arindam200** [comment]
@Sirsha2468  go for it

**Comment by Sirsha2468** [comment]
> 

I have already contributed, and sent you pull request. Please check once

**Comment by Sirsha2468** [comment]
@Arindam200 Can you please accept my PR? Or If there any changes needed feel free to tell me. Thank you.

**Comment by vikash485** [comment]
Hey @Arindam200, I have a made a contribution pr for this issue, please verify and merge. Thanks

**Comment by yashraj0114** [comment]
Hey @Arindam200  I want to contribute to this project please assign me on this.

**Comment by Arindam200** [comment]
@yashraj0114 make PR! I'll merge

**Comment by yashraj0114** [comment]
@Arindam200 ok brother I am making

**Comment by yashraj0114** [comment]
@Arindam200  bro can you see I have make pull request .Have you merge it

**Comment by yashraj0114** [comment]
@Arindam200 hey bro please let me know if there has to be any changes and I will see , merge it

**Comment by chiragbiradar** [comment]
@Arindam200 I can add card game in python. Can you assign me this?
